name: Development Tools
apps:
    - name: Redmine
      desc: Issues Tracker
      url: http://www.redmine.org/
      oss: GPL
      cost: 0

    - name: GitLab
      desc: Git repository management
      url: https://about.gitlab.com/
      oss: GPL
      cost: 1

    - name: Jenkins
      desc: Continous Integration
      url: http://jenkins-ci.org/
      oss: MIT
      cost: 0

    - name: Piwik
      desc: Web Analytics
      url: http://piwik.org/
      oss: GPL
      cost: 1

    - name: Gogs
      desc: Git service
      url: http://gogs.io/
      oss: MIT
      cost: 0

    - name: DreamFactory
      desc: Backend plattform
      url: https://www.dreamfactory.com/
      oss: AL
      cost: 0
